### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by cloudscape-germany**
Updating "smtp-connection" to "^4.0.2"

https://snyk.io/advisor/npm-package/nodemailer-smtp-transport

### CODE REVIEW

**Review by KonstantinModin — APPROVED** [review]

**Comment by KonstantinModin** [comment]
updated version you can find here:  
**npm i nodemailer-smtp-transport-upd**

**Comment by cope** [comment]
when can this be merged, please?

**Comment by cope** [comment]
shouldn't the version upped from 2.7.4 to 2.7.5, as well?

**Comment by andris9** [comment]
[nodemailer-smtp-transport](https://github.com/nodemailer/nodemailer-smtp-transport) module is only needed for extremely old Nodemailer versions. Any Nodemailer version released in the last 5 years, has this built-in and does not require this module. The module only exists for legacy compatibility and is not updated anymore.

**Comment by cope** [comment]
@andris9 the issue is a few levels deeper, namely underscore 1.7.0

```
nodemailer-smtp-transport@2.7.4			- latest
|----->	smtp-connection@2.12.0			- latest is 4.0.2
	|----->	httpntlm@1.6.1			- latest is 1.8.13
		|----->	underscore@1.7.0	- latest is 1.13.6
```

so, as long as nodemailer-smtp-transport, the vulnerability will remain :(

**Comment by andris9** [comment]
nodemailer-smtp-transport does not use that functionality from underscore that triggers that vulnerability, so the issue is only with the security scanner that reports a false positive (the module with a vulnerability is included but not used). Unless there is a proven security issue with nodemailer-smtp-transport itself, there will be no more updates. This is to push people to move away from nodemailer-smtp-transport (there hasn't been any reason to use it for at least 5+ years).

**Pull request closed without merging**
